### PR TITLE
Proposal/issue 44

### PR DESCRIPTION
**Pull request by rosta**
Correction to reportLinesUnchanged / showInlineDiffs incompatibility

Possible implementation of rawValue option

### CODE REVIEW

**Comment by rosta** [comment]
I'm beginning to think that this might not be the best solution.

A better way forward might be to split the diffing and the formatting into two phases and let the client code call appropriate formatting routines directly. However that would mean that differences are calculated twice. Once when differences are found and classified, and once when the diff marker tags are interpolated into the formatted text.

Hmmm...

**Comment by wumpz** [comment]
The diffing and formatting are done in two phases, IMHO.  How do you want to split it?

**Comment by rosta** [comment]
Yes, I hear what you say. I don't mean to dish what has already been done _and works_.

It's just that I haven't yet found how to get the output I need. Worse, I don't even know what that is exactly :-( I'll be looking at that this week. Please don't do anything with this PR for the moment until I can update it.

**Comment by wumpz** [comment]
Would it be an improvement, if you don't use the default line normalizer? `LINE_NORMALIZER_FOR_HTML` simply calls `StringUtils::normalize`. Without it, you would not have those html tags preprocessed. I know this is not a complete solution.

**Comment by rosta** [comment]
I rolled back most of the changes. Just left a single correction.

FI: I replaced the lineNormalizer in my code to the identity function, and renormalize afterwards.

Sorry to take so long with this but I had other things ongoing!

**Pull request merged**
